version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
build_script:
 - ps: |
     $ErrorActionPreference = "continue"
     powershell -File "$env:APPVEYOR_BUILD_FOLDER\build-cairo.ps1"

artifacts:
  - path: cairo.zip
    name: cairo
  - path: cairo/*
    name: cairo1

