version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
          
build_script:
 - ps: |
     $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
     $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
     bash -lc "unset TMP"
     bash -lc "unset TEMP"
     echo "$env:VS120COMNTOOLS"
     # Start-Process -FilePath "$($env:VS120COMNTOOLS)VsDevCmd.bat"; echo $env:PATH; 
     # cmd.exe /C '"C:\msys64\msys2_shell.cmd" -defterm -no-start -use-full-path'
     cmd /C RefreshEnv.cmd
     cmd.exe /C "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat -host_arch=amd64 -arch=x64 && echo %PATH%"
     $USE_FREETYPE=1
     $CAIRO_VERSION="cairo-1.17.2"
     $PIXMAN_VERSION="pixman-0.40.0"
     $LIBPNG_VERSION="libpng-1.6.37"
     $ZLIB_VERSION="zlib-1.2.11"
     $FREETYPE_VERSION="freetype-2.10.2"
     $MSVC_PLATFORM_NAME='x64'
     wget -nc -q https://www.cairographics.org/snapshots/$CAIRO_VERSION.tar.xz
     wget -nc -q https://www.cairographics.org/releases/$PIXMAN_VERSION.tar.gz
     wget -nc -q https://download.sourceforge.net/libpng/$LIBPNG_VERSION.tar.gz
     wget -nc -q http://www.zlib.net/$ZLIB_VERSION.tar.gz
     wget -nc -q http://download.savannah.gnu.org/releases/freetype/$FREETYPE_VERSION.tar.gz
     tar -xJf $CAIRO_VERSION.tar.xz
     move $CAIRO_VERSION cairo
     tar -xzf $PIXMAN_VERSION.tar.gz
     move $PIXMAN_VERSION pixman
     tar -xzf $LIBPNG_VERSION.tar.gz
     move $LIBPNG_VERSION libpng
     tar -xzf $ZLIB_VERSION.tar.gz
     move $ZLIB_VERSION zlib
     tar -xzf $FREETYPE_VERSION.tar.gz
     move $FREETYPE_VERSION freetype
     cd libpng
     bash -c "sed 's#4996</Disable#4996;5045</Disable#' projects/vstudio/zlib.props > zlib.props.fixed"
     move zlib.props.fixed projects/vstudio/zlib.props
     devenv.com "projects\vstudio\vstudio.sln" -upgrade
     devenv.com "projects\vstudio\vstudio.sln" -build "Release Library|$MSVC_PLATFORM_NAME" -project libpng
     cd ..
     cp "libpng/projects/vstudio/x64/Release Library/libpng16.lib" libpng/libpng.lib
     cp "libpng/projects/vstudio/x64/Release Library/zlib.lib" zlib/zlib.lib
     

     

