version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
          
build_script:
 - ps: |
     $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
     $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
     bash -lc "unset TMP"
     bash -lc "unset TEMP"
     echo "$env:VS120COMNTOOLS"
     # Start-Process -FilePath "$($env:VS120COMNTOOLS)VsDevCmd.bat"; echo $env:PATH; 
     # cmd.exe /C '"C:\msys64\msys2_shell.cmd" -defterm -no-start -use-full-path'
     cmd /C RefreshEnv.cmd
     cmd.exe /C "C:\BuildTools\Common7\Tools\VsDevCmd.bat -host_arch=amd64 -arch=$env:ARCH"
     set MSYS=winsymlinks:nativestrict
     bash -lc "./build-cairo-windows.sh"

