version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
        git clone https://gitlab.freedesktop.org/cairo/cairo.git
build_script:
 - ps: |
      $ErrorActionPreference = "continue"      
      Write-Output "Setting enviroment variable using vswhere"
      # from https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt#using-powershell
      $installationPath = vswhere.exe -prerelease -latest -property installationPath
      if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
          & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo && set" | foreach-object {
              $name, $value = $_ -split '=', 2
              set-content env:\"$name" $value
          }
      }
      $env:PATH="C:\Python38-x64;C:\Python38-x64\Scripts;$env:PATH"
      #wget "https://gitlab.freedesktop.org/cairo/cairo/-/archive/master/cairo-master.zip" -o "cairo.zip"
      #7z x cairo.zip -ocairo
      cd cairo
      pip install --upgrade meson ninja
      meson build --default-library=both -Dfontconfig=enabled -Dfreetype=enabled -Dglib=enabled -Dzlib=enabled
      ninja -C build
      Copy-Item cairo/build $OUTPUT_FOLDER
      7z a cairo.zip build
      echo 'Success!'


artifacts:
  - path: cairo.zip
    name: cairo
  - path: cairo/**
    name: cairo1

