version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
        git clone https://gitlab.freedesktop.org/cairo/cairo.git
build_script:
 - ps: |
      $ErrorActionPreference = "continue"
      mkdir x86
      cd x86
      Copy-Item -Path "$PWD\..\cairo" -Destination "$PWD\cairo" –Recurse
      cd ../
      tree
      cd x86
      Write-Output "Setting enviroment variable using vswhere"
      # from https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt#using-powershell
      $prevPath= $env:PATH
      $installationPath = vswhere.exe -prerelease -latest -property installationPath
      if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
          & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo -host_arch=amd64 -arch=x86 && set" | foreach-object {
              $name, $value = $_ -split '=', 2
              set-content env:\"$name" $value
          }
      }
      $env:PATH="C:\Python38-x64;C:\Python38-x64\Scripts;$env:PATH"
      pip install --upgrade meson ninja
      meson --default-library=shared --prefix=C:\cairo\x86 --buildtype release -Dfontconfig=enabled -Dfreetype=enabled -Dglib=enabled -Dzlib=enabled -Dtee=enabled cairo_builddir cairo
      meson compile -C cairo_builddir
      meson install -C cairo_builddir
      cd ../
      mkdir x64
      cd x64
      $installationPath = vswhere.exe -prerelease -latest -property installationPath
      if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
          & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo -host_arch=amd64 -arch=amd64 && set" | foreach-object {
              $name, $value = $_ -split '=', 2
              set-content env:\"$name" $value
          }
      }
      Copy-Item -Path "$PWD\..\cairo" -Destination "$PWD\cairo" –Recurse
      $env:PATH="C:\Python38-x64;C:\Python38-x64\Scripts;$env:PATH"
      pip install --upgrade meson ninja
      meson --default-library=shared --prefix=C:\cairo\x64 --buildtype release -Dfontconfig=enabled -Dfreetype=enabled -Dglib=enabled -Dzlib=enabled -Dtee=enabled cairo_builddir cairo
      meson compile -C cairo_builddir
      meson install -C cairo_builddir
      $env:PATH = $prevPath
      7z a cairo_x86.zip x86\cairo_builddir
      7z a cairo_x64.zip x64\cairo_builddir
      7z a cairo_release.zip C:\cairo
      echo 'Success!'


artifacts:
  - path: cairo.zip
    name: cairo
  - path: cairo_release.zip
    name: cairo1

