version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
        choco install make
           
build_script:
 - cmd: |
     set CHERE_INVOKING = 'yes'  # Preserve the current working directory
     set MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
     bash -lc "unset TMP"
     bash -lc "unset TEMP"
     powershell build-cairo.ps1
     Get-Command "vswhere"
     Get-Command "msbuild"


