version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit
  CHERE_INVOKING: 1  
install:
 - cmd: |
        choco install wget
        C:\msys64\usr\bin\bash -lc "rm -r /etc/pacman.d/gnupg/"
        C:\msys64\usr\bin\bash -lc "pacman-key --init"
        C:\msys64\usr\bin\bash -lc "pacman-key --populate msys2"
        C:\msys64\usr\bin\bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
        C:\msys64\usr\bin\bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
        C:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
        C:\msys64\usr\bin\bash -lc "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
        C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syyuu"
        taskkill /F /IM gpg-agent.exe
        taskkill /F /IM dirmngr.exe
        C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
        C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S tar make"
build_script:
 - ps: |
      $ErrorActionPreference = "continue"      
      Write-Output "Setting enviroment variable using vswhere"
      # from https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt#using-powershell
      $prevPath= $env:PATH
      $installationPath = vswhere.exe -prerelease -latest -property installationPath
      if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
          & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo -host_arch=amd64 -arch=x86 && set" | foreach-object {
              $name, $value = $_ -split '=', 2
              set-content env:\"$name" $value
          }
      }
      $env:MSYSTEM = 'MINGW64'
      $env:PATH="C:\msys64;$env:PATH"
      C:\msys64\usr\bin\bash -c "unset TMP"
      C:\msys64\usr\bin\bash -c "unset TEMP"
      C:\msys64\usr\bin\bash -c "which tar"
      C:\msys64\usr\bin\bash -x "./build-cairo-windows.sh"
      7z a cairo_x86.zip output
      echo 'Success!'
artifacts:
  - path: cairo_x86.zip
    name: cairo_x86

