version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
        choco install wget
        choco install make
           
build_script:
 - ps: |
     $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
     $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
     bash -lc "unset TMP"
     bash -lc "unset TEMP"
     echo "$env:VS120COMNTOOLS"
     # Start-Process -FilePath "$($env:VS120COMNTOOLS)VsDevCmd.bat"; echo $env:PATH; 
     # cmd.exe /C '"C:\msys64\msys2_shell.cmd" -defterm -no-start -use-full-path'
     cmd /C RefreshEnv.cmd
     cmd.exe /C ''"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=x64 && powershell build-cairo.ps1'
     Get-Command "vswhere"
     Get-Command "msbuild"


