version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

install:
 - cmd: |
     set PATH=C:\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
     C:\msys64\usr\bin\bash -lc "rm -r /etc/pacman.d/gnupg/"
     C:\msys64\usr\bin\bash -lc "pacman-key --init"
     C:\msys64\usr\bin\bash -lc "pacman-key --populate msys2"
     C:\msys64\usr\bin\bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
     C:\msys64\usr\bin\bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
     C:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
     C:\msys64\usr\bin\bash -lc "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
     C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
     taskkill /F /IM gpg-agent.exe
     taskkill /F /IM dirmngr.exe
     C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm tar make"
          
build_script:
 - ps: |
     $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
     $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
     bash -lc "unset TMP"
     bash -lc "unset TEMP"
     echo "$env:VS120COMNTOOLS"
     & "$env:VS120COMNTOOLSVsDevCmd.bat" & echo $env:PATH & C:\msys64\msys2_shell.cmd -defterm -no-start -use-full-path
     bash -lc "./build-cairo-windows.sh"

