version: '{build}'
max_jobs: 1
build: off
test: off
deploy: off
image: Visual Studio 2017

environment:
  MSYS2_PATH_TYPE: inherit

init:
 - cmd: |
     set PATH=C:\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
     curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
     curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
     C:\msys64\usr\bin\bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
     C:\msys64\usr\bin\pacman --noconfirm -Syyuu
     C:\msys64\usr\bin\pacman --noconfirm -Syuu
          
build_script:
 - ps: |
     $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
     $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
     bash -lc "pacman -S --noconfirm tar make"
     $env:PATH="$PWD\msys64\usr\bin;$env:PATH"
     bash -lc "./build-cairo-windows.sh"
