name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Build x64 Build
        continue-on-error: true
        run: |
           $env:PATH="C:\msys64\usr\bin;C:\msys64\bin;$($env:PATH)"
           dir env:
           & "$($env:VS140COMNTOOLS)\vsvars32.bat"
           $ROOTDIR="$($PWD)\BuildCairo"
           mkdir "$ROOTDIR"
           cd "$ROOTDIR"
           #C:\msys64\usr\bin\bash -lc './build-cairo-windows.sh'
