name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Build x64 Build
        continue-on-error: true
        run: |
           $env:PATH="C:\msys64\usr\bin;C:\msys64\bin;$($env:PATH)"
           dir "$($env:VS140COMNTOOLS)"
           & "$($env:VS140COMNTOOLS)\vsvars32.bat"
           $ROOTDIR="$($PWD)\BuildCairo"
           mkdir "$ROOTDIR"
           cd "$ROOTDIR"
           # Update MSYS2
           bash -lc "pacman --noconfirm -Syuu"  # Core update (in case any core packages are outdated)
           bash -lc "pacman --noconfirm -Syuu"  # Normal update
           bash -lc "pacman --noconfirm -S tar make"
           $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
           $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
           curl http://www.zlib.net/zlib-1.2.3.tar.gz -o zlib.tgz
           curl ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng-1.2.40.tar.gz -o libpng.tgz
           curl http://www.cairographics.org/releases/pixman-0.16.2.tar.gz -o pixman.tgz
           curl http://www.cairographics.org/releases/cairo-1.8.8.tar.gz -o cairo.tgz
           tar -xzf zlib.tgz
           tar -xzf libpng.tgz
           tar -xzf pixman.tgz
           tar -xzf cairo.tgz
           move zlib-* zlib
           move libpng-* libpng
           move pixman-* pixman
           move cairo-* cairo
           bash -lc "cmd.exe /C `"%VS140COMNTOOLS%\VsDevCmd.bat`""
           bash -lc "../build-cairo-windows.sh"
           mkdir "$($ROOTDIR)\zlib\projects\visualc71"
           cd "$($ROOTDIR)\zlib\projects\visualc71"
           copy "$($ROOTDIR)\libpng\projects\visualc71\zlib.vcproj ."
           #bash -lc "./build-cairo-windows.sh"
           #C:\msys64\usr\bin\bash -lc './build-cairo-windows.sh'
