name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain make tar
      - name: Install VS2017
        run: choco install visualstudio2017community
      - name: Build x64 Build
        continue-on-error: true
        run: |
           $env:PATH="C:\msys64\usr\bin;C:\msys64\bin;$($env:PATH)"
           dir env:
           #C:\msys64\usr\bin\bash -lc './build-cairo-windows.sh'
