name: CI

on:
  push:

jobs:
  build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Install Wget
        run: |
          choco install wget
      - name: Execute Script
        continue-on-error: true
        run: |
            $installationPath = vswhere.exe -prerelease -latest -property installationPath
            if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
              & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo && set" | foreach-object {
                $name, $value = $_ -split '=', 2
                set-content env:\"$name" $value
              }
            }
            bash "./build-cairo-windows.sh"
      - uses: actions/upload-artifact@v2
        with:
          name: cairo.makefile
          path: cairo/src/Makefile.win32
      - uses: actions/upload-artifact@v2
        with:
          name: cairo.makefile.edited
          path: cairo/build/Makefile.win32.common
      - uses: actions/upload-artifact@v2
        with:
          name: cairo.x86
          path: output
