name: Build

on: [push]

jobs:
  build_cairo:
    name: Build cairo for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Build x64 Build
        continue-on-error: true
        run: |
           $env:PATH="C:\msys64\usr\bin;C:\msys64\bin;$($env:PATH)"
           dir env:
           & "$($env:VS140COMNTOOLS)\vsvars32.bat"
           $ROOTDIR="$($PWD)\BuildCairo"
           mkdir "$ROOTDIR"
           cd "$ROOTDIR"
           # Update MSYS2
           bash -lc "pacman --noconfirm -Syuu"  # Core update (in case any core packages are outdated)
           bash -lc "pacman --noconfirm -Syuu"  # Normal update
           bash -lc "pacman --noconfirm -S tar make"
           $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
           $env:MSYSTEM = 'MINGW64'  # Start a 64 bit Mingw environment
           C:\msys64\usr\bin\bash -lc "./ci-build.sh"
           #C:\msys64\usr\bin\bash -lc './build-cairo-windows.sh'
